USE SPMEDICALGROUP_TARDE;
GO

--Criando Procedures
CREATE PROCEDURE INSERIR_DADOS_ESTATICOS
AS
BEGIN
	INSERT INTO TIPO_USUARIO(NOME)
		VALUES ('Administrador'),('Médico'),('Paciente')
	SELECT * FROM TIPO_USUARIO

	INSERT INTO TIPO_STATUS(NOME)
		VALUES('Confirmada'), ('Recusada'), ('Adiada'), ('Aguardando confirmação do médico'), ('Realizada'), ('Cancelada'), ('Agendada')
	SELECT * FROM TIPO_STATUS

	INSERT INTO CLINICA(NOME, RAZAO_SOCIAL, CNPJ, HORARIO_FUNCIONAMENTO,LOCALIDADE)
		VALUES ('SP Medical Group', 'SP MEDICAL GROUP', '12345678910111', 'Das 7hs às 19hs', 'Alameda Barão de Limeira, 539 - Santa Cecilia, São Paulo - SP, 01202-001')

	INSERT INTO USUARIOS(NOME, EMAIL, SENHA, ID_TIPO_USUARIO, ID_CLINICA)
		VALUES ('admin', 'admin@admin.com', 'admin', 1, 1)
END
GO

CREATE PROCEDURE INSERIR_ESPECIALIDADES
AS
BEGIN
	BULK INSERT ESPECIALIDADES
	FROM 'C:\SPMEDGROUP\Especialidades.csv'
		WITH(
			FORMAT = 'csv',
			FIRSTROW = 2,
			FIELDTERMINATOR = ';',
			ROWTERMINATOR = '\n',
			CODEPAGE = 'ACP',
			DATAFILETYPE = 'Char'
		);
	SELECT * FROM ESPECIALIDADES
END
GO

CREATE PROCEDURE INSERIR_USUARIOS
AS
BEGIN
	BULK INSERT USUARIOS
	FROM 'C:\SPMEDGROUP\Usuários.csv'
		WITH(
			FORMAT = 'csv',
			FIRSTROW = 2,
			FIELDTERMINATOR = ';',
			ROWTERMINATOR = '\n',
			CODEPAGE = 'ACP',
			DATAFILETYPE = 'Char'
		);
	SELECT * FROM USUARIOS
END
GO

CREATE PROCEDURE INSERIR_MEDICOS
AS
BEGIN
	BULK INSERT MEDICOS
	FROM 'C:\SPMEDGROUP\Médicos.csv'
		WITH(
			FORMAT = 'csv',
			FIRSTROW = 2,
			FIELDTERMINATOR = ';',
			ROWTERMINATOR = '\n',
			CODEPAGE = 'ACP',
			DATAFILETYPE = 'Char'
		);
	SELECT * FROM MEDICOS
END
GO

CREATE PROCEDURE INSERIR_PACIENTES
AS
BEGIN
	BULK INSERT PACIENTES
	FROM 'C:\SPMEDGROUP\Pacientes.csv'
		WITH(
			FORMAT = 'csv',
			FIRSTROW = 2,
			FIELDTERMINATOR = ';',
			ROWTERMINATOR = '\n',
			CODEPAGE = 'ACP',
			DATAFILETYPE = 'Char'
		);
	SELECT * FROM PACIENTES
END
GO

CREATE PROCEDURE INSERIR_CONSULTAS
AS
BEGIN
	BULK INSERT CONSULTAS
	FROM 'C:\SPMEDGROUP\Consultas.csv'
		WITH(
			FORMAT = 'csv',
			FIRSTROW = 2,
			FIELDTERMINATOR = ';',
			ROWTERMINATOR = '\n',
			CODEPAGE = 'ACP',
			DATAFILETYPE = 'Char'
		);
	SELECT * FROM CONSULTAS
END
GO

--CALCULAR IDADE
CREATE PROCEDURE CALCULAR_IDADE_PACIENTE
	@ID_PACIENTE INT
AS
BEGIN
	DECLARE @DATA_NASCIMENTO DATETIME
	SET @DATA_NASCIMENTO = (SELECT DATA_NASCIMENTO FROM PACIENTES WHERE ID = @ID_PACIENTE)

	SELECT FLOOR(DATEDIFF(DAY, @DATA_NASCIMENTO, GETDATE()) / 365.25) AS IDADE_DO_PACIENTE
END
GO

--CONTAR MÉDICOS POR ESPECIALIDADE
CREATE PROCEDURE MEDICO_POR_IDESPECIALIDADE
	@ESPECIALIDADE VARCHAR(255)
AS
BEGIN
	SELECT COUNT(ID) AS MEDICOS_POR_ESPECIALIDADE FROM MEDICOS WHERE ID_ESPECIALIDADE = @ESPECIALIDADE
END
GO

CREATE PROCEDURE BACKUP_BD
AS
BEGIN
	BACKUP DATABASE SPMEDICALGROUP_TARDE
	TO DISK = 'C:\db\SPMEDICALGROUP_BD_ARIEL.BAK'
END
GO

--Executando Procedures
EXEC INSERIR_ESPECIALIDADES
EXEC INSERIR_USUARIOS
EXEC INSERIR_MEDICOS
EXEC INSERIR_PACIENTES
EXEC INSERIR_CONSULTAS
EXEC INSERIR_DADOS_ESTATICOS -- Executar está procedure em último lugar.
EXEC BACKUP_BD

EXEC CALCULAR_IDADE_PACIENTE 2
EXEC MEDICO_POR_IDESPECIALIDADE 2